### ISSUE TITLE
KeyError: 'only_ocean_sources'???why?

### ISSUE THREAD

**Issue by HanyuZhang520** [lermert/noisi#9]
Step 2: Creating a source grid

create the source grid
!noisi setup_sourcegrid example
# show the sketch of the source grid
#Image('example/sourcegrid.png', width=400)

result:

Configuration used to set up source grid:
{'date_created': '2024.12.19',
 'grid_dx_in_m': 35000,
 'grid_lat_max': 65,
 'grid_lat_min': 30,
 'grid_lon_max': 25,
 'grid_lon_min': -15,
 'ocean_only_sources': True,
 'project_name': 'example',
 'project_path': '/mnt/d/DAS_ZXP_20231227/noisi/noisi/examples/example',
 'random_shift_longitude': False,
 'synt_data': 'DIS',
 'verbose': True,
 'wavefield_channel': 'Z',
 'wavefield_domain': 'time',
 'wavefield_duration': 800.0,
 'wavefield_filter': [0.01, 0.2],
 'wavefield_path': 'x',
 'wavefield_point_force': '1.0e6',
 'wavefield_sampling_rate': 0.5,
 'wavefield_type': 'analytic'}
Number of gridpoints:  9520
Traceback (most recent call last):
  File "/home/zhy/anaconda3/envs/noisi_py3.8/bin/noisi", line 33, in <module>
    sys.exit(load_entry_point('noisi==0.1.0a0', 'console_scripts', 'noisi')())
  File "/home/zhy/anaconda3/envs/noisi_py3.8/lib/python3.8/site-packages/noisi-0.1.0a0-py3.8.egg/noisi/main.py", line 172, in run
    args.func(args, comm, size, rank)
  File "/home/zhy/anaconda3/envs/noisi_py3.8/lib/python3.8/site-packages/noisi-0.1.0a0-py3.8.egg/noisi/scripts/source_grid.py", line 49, in setup_sourcegrid
    if config["only_ocean_sources"]:
KeyError: 'only_ocean_sources'

​

**Comment by HofaceEl** [comment]
Changing the parameter from ocean_only_sources to only_ocean_sources at line 12 in config.yml seems to resolve the issue. Looks it was a simple KeyError, yet no contributor has addressed it so far.
